name: Build and publish Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - '*.*.*'

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 1
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (for main branch)
        if: github.ref == 'refs/heads/main'
        id: docker_build_main
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            xscanner/runner:${{ steps.time.outputs.time }}
            xscanner/runner:latest

      - name: Build and push (for tags)
        if: startsWith(github.ref, 'refs/tags/')
        id: docker_build_tag
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            xscanner/runner:${{ steps.vars.outputs.tag }}
